%% make_contrasts
% A script which quickly whips up contrasts. 

%% Parameters
cons = { ...
    'S70'  ...
    'C70'  ...
    'S140' ...
    'C140' ...
    'ODD'  ...
    'SIL'  ...
    };

move = {...
    'mov1'...
    'mov2'...
    'mov3'...
    'mov4'...
    'mov5'...
    'mov6'...
    };

phys = {...
    'phy1'...
    'phy2'...
    'phy3'...
    'phy4'...
%     'err1'...
    };

artr = {...
    'art1'...
    'art2'...
    'art3'...
    'art4'...
    };

regs = horzcat(move, phys, artr); 
full = horzcat(cons, regs);

numCons = length(cons);
numRegs = length(regs);
numRun1 = length(full); 

%% Contrasts
contrast_identity.short_long = [-1 -1  1  1  0  0];
contrast_identity.long_short = [ 1  1 -1 -1  0  0];
contrast_identity.sim_com = [ 1 -1  1 -1  0  0];
contrast_identity.com_sim = [-1  1 -1  1  0  0];

contrasts = fields(contrast_identity);

%% Make contrasts
% Hybrid
numBins = 10;
for ii = 1:length(contrasts)
    c.(contrasts{ii}).identity = [];
    for jj = 1:numCons
        c.(contrasts{ii}).identity = horzcat(c.(contrasts{ii}).identity, repmat(contrast_identity.(contrasts{ii})(jj), 1, numBins));
    end
    c.(contrasts{ii}).r1 = c.(contrasts{ii}).identity; 
    c.(contrasts{ii}).r2 = horzcat(zeros(1, length(c.(contrasts{ii}).identity) + numRegs), c.(contrasts{ii}).identity);
    c.(contrasts{ii}).all = horzcat(c.(contrasts{ii}).identity, zeros(1, numRegs), c.(contrasts{ii}).identity);
end
